export interface Nationality {
  code: string
  name: string
  flag: string
}

export const NATIONALITIES: Nationality[] = [
  { code: 'AF', name: 'Afghan', flag: '🇦🇫' },
  { code: 'AL', name: 'Albanian', flag: '🇦🇱' },
  { code: 'DZ', name: 'Algerian', flag: '🇩🇿' },
  { code: 'AD', name: 'Andorran', flag: '🇦🇩' },
  { code: 'AO', name: 'Angolan', flag: '🇦🇴' },
  { code: 'AG', name: 'Antiguan and Barbudan', flag: '🇦🇬' },
  { code: 'AR', name: 'Argentine', flag: '🇦🇷' },
  { code: 'AM', name: 'Armenian', flag: '🇦🇲' },
  { code: 'AU', name: 'Australian', flag: '🇦🇺' },
  { code: 'AT', name: 'Austrian', flag: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaijani', flag: '🇦🇿' },
  { code: 'BS', name: 'Bahamian', flag: '🇧🇸' },
  { code: 'BH', name: 'Bahraini', flag: '🇧🇭' },
  { code: 'BD', name: 'Bangladeshi', flag: '🇧🇩' },
  { code: 'BB', name: 'Barbadian', flag: '🇧🇧' },
  { code: 'BY', name: 'Belarusian', flag: '🇧🇾' },
  { code: 'BE', name: 'Belgian', flag: '🇧🇪' },
  { code: 'BZ', name: 'Belizean', flag: '🇧🇿' },
  { code: 'BJ', name: 'Beninese', flag: '🇧🇯' },
  { code: 'BT', name: 'Bhutanese', flag: '🇧🇹' },
  { code: 'BO', name: 'Bolivian', flag: '🇧🇴' },
  { code: 'BA', name: 'Bosnian and Herzegovinian', flag: '🇧🇦' },
  { code: 'BW', name: 'Motswana', flag: '🇧🇼' },
  { code: 'BR', name: 'Brazilian', flag: '🇧🇷' },
  { code: 'BN', name: 'Bruneian', flag: '🇧🇳' },
  { code: 'BG', name: 'Bulgarian', flag: '🇧🇬' },
  { code: 'BF', name: 'Burkinabé', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundian', flag: '🇧🇮' },
  { code: 'CV', name: 'Cape Verdean', flag: '🇨🇻' },
  { code: 'KH', name: 'Cambodian', flag: '🇰🇭' },
  { code: 'CM', name: 'Cameroonian', flag: '🇨🇲' },
  { code: 'CA', name: 'Canadian', flag: '🇨🇦' },
  { code: 'CF', name: 'Central African', flag: '🇨🇫' },
  { code: 'TD', name: 'Chadian', flag: '🇹🇩' },
  { code: 'CL', name: 'Chilean', flag: '🇨🇱' },
  { code: 'CN', name: 'Chinese', flag: '🇨🇳' },
  { code: 'CO', name: 'Colombian', flag: '🇨🇴' },
  { code: 'KM', name: 'Comorian', flag: '🇰🇲' },
  { code: 'CG', name: 'Congolese', flag: '🇨🇬' },
  { code: 'CD', name: 'Congolese (DRC)', flag: '🇨🇩' },
  { code: 'CR', name: 'Costa Rican', flag: '🇨🇷' },
  { code: 'HR', name: 'Croatian', flag: '🇭🇷' },
  { code: 'CU', name: 'Cuban', flag: '🇨🇺' },
  { code: 'CY', name: 'Cypriot', flag: '🇨🇾' },
  { code: 'CZ', name: 'Czech', flag: '🇨🇿' },
  { code: 'DK', name: 'Danish', flag: '🇩🇰' },
  { code: 'DJ', name: 'Djiboutian', flag: '🇩🇯' },
  { code: 'DM', name: 'Dominican', flag: '🇩🇲' },
  { code: 'DO', name: 'Dominican (Rep.)', flag: '🇩🇴' },
  { code: 'EC', name: 'Ecuadorian', flag: '🇪🇨' },
  { code: 'EG', name: 'Egyptian', flag: '🇪🇬' },
  { code: 'SV', name: 'Salvadoran', flag: '🇸🇻' },
  { code: 'GQ', name: 'Equatoguinean', flag: '🇬🇶' },
  { code: 'ER', name: 'Eritrean', flag: '🇪🇷' },
  { code: 'EE', name: 'Estonian', flag: '🇪🇪' },
  { code: 'SZ', name: 'Swazi', flag: '🇸🇿' },
  { code: 'ET', name: 'Ethiopian', flag: '🇪🇹' },
  { code: 'FJ', name: 'Fijian', flag: '🇫🇯' },
  { code: 'FI', name: 'Finnish', flag: '🇫🇮' },
  { code: 'FR', name: 'French', flag: '🇫🇷' },
  { code: 'GA', name: 'Gabonese', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambian', flag: '🇬🇲' },
  { code: 'GE', name: 'Georgian', flag: '🇬🇪' },
  { code: 'DE', name: 'German', flag: '🇩🇪' },
  { code: 'GH', name: 'Ghanaian', flag: '🇬🇭' },
  { code: 'GR', name: 'Greek', flag: '🇬🇷' },
  { code: 'GD', name: 'Grenadian', flag: '🇬🇩' },
  { code: 'GT', name: 'Guatemalan', flag: '🇬🇹' },
  { code: 'GN', name: 'Guinean', flag: '🇬🇳' },
  { code: 'GW', name: 'Bissau-Guinean', flag: '🇬🇼' },
  { code: 'GY', name: 'Guyanese', flag: '🇬🇾' },
  { code: 'HT', name: 'Haitian', flag: '🇭🇹' },
  { code: 'HN', name: 'Honduran', flag: '🇭🇳' },
  { code: 'HU', name: 'Hungarian', flag: '🇭🇺' },
  { code: 'IS', name: 'Icelandic', flag: '🇮🇸' },
  { code: 'IN', name: 'Indian', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonesian', flag: '🇮🇩' },
  { code: 'IR', name: 'Iranian', flag: '🇮🇷' },
  { code: 'IQ', name: 'Iraqi', flag: '🇮🇶' },
  { code: 'IE', name: 'Irish', flag: '🇮🇪' },
  { code: 'IL', name: 'Israeli', flag: '🇮🇱' },
  { code: 'IT', name: 'Italian', flag: '🇮🇹' },
  { code: 'JM', name: 'Jamaican', flag: '🇯🇲' },
  { code: 'JP', name: 'Japanese', flag: '🇯🇵' },
  { code: 'JO', name: 'Jordanian', flag: '🇯🇴' },
  { code: 'KZ', name: 'Kazakhstani', flag: '🇰🇿' },
  { code: 'KE', name: 'Kenyan', flag: '🇰🇪' },
  { code: 'KI', name: 'I-Kiribati', flag: '🇰🇮' },
  { code: 'KP', name: 'North Korean', flag: '🇰🇵' },
  { code: 'KR', name: 'South Korean', flag: '🇰🇷' },
  { code: 'KW', name: 'Kuwaiti', flag: '🇰🇼' },
  { code: 'KG', name: 'Kyrgyz', flag: '🇰🇬' },
  { code: 'LA', name: 'Lao', flag: '🇱🇦' },
  { code: 'LV', name: 'Latvian', flag: '🇱🇻' },
  { code: 'LB', name: 'Lebanese', flag: '🇱🇧' },
  { code: 'LS', name: 'Basotho', flag: '🇱🇸' },
  { code: 'LR', name: 'Liberian', flag: '🇱🇷' },
  { code: 'LY', name: 'Libyan', flag: '🇱🇾' },
  { code: 'LI', name: 'Liechtensteinish', flag: '🇱🇮' },
  { code: 'LT', name: 'Lithuanian', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourgish', flag: '🇱🇺' },
  { code: 'MG', name: 'Malagasy', flag: '🇲🇬' },
  { code: 'MW', name: 'Malawian', flag: '🇲🇼' },
  { code: 'MY', name: 'Malaysian', flag: '🇲🇾' },
  { code: 'MV', name: 'Maldivian', flag: '🇲🇻' },
  { code: 'ML', name: 'Malian', flag: '🇲🇱' },
  { code: 'MT', name: 'Maltese', flag: '🇲🇹' },
  { code: 'MH', name: 'Marshallese', flag: '🇲🇭' },
  { code: 'MR', name: 'Mauritanian', flag: '🇲🇷' },
  { code: 'MU', name: 'Mauritian', flag: '🇲🇺' },
  { code: 'MX', name: 'Mexican', flag: '🇲🇽' },
  { code: 'FM', name: 'Micronesian', flag: '🇫🇲' },
  { code: 'MD', name: 'Moldovan', flag: '🇲🇩' },
  { code: 'MC', name: 'Monégasque', flag: '🇲🇨' },
  { code: 'MN', name: 'Mongolian', flag: '🇲🇳' },
  { code: 'ME', name: 'Montenegrin', flag: '🇲🇪' },
  { code: 'MA', name: 'Moroccan', flag: '🇲🇦' },
  { code: 'MZ', name: 'Mozambican', flag: '🇲🇿' },
  { code: 'MM', name: 'Burmese', flag: '🇲🇲' },
  { code: 'NA', name: 'Namibian', flag: '🇳🇦' },
  { code: 'NR', name: 'Nauruan', flag: '🇳🇷' },
  { code: 'NP', name: 'Nepali', flag: '🇳🇵' },
  { code: 'NL', name: 'Dutch', flag: '🇳🇱' },
  { code: 'NZ', name: 'New Zealander', flag: '🇳🇿' },
  { code: 'NI', name: 'Nicaraguan', flag: '🇳🇮' },
  { code: 'NE', name: 'Nigerien', flag: '🇳🇪' },
  { code: 'NG', name: 'Nigerian', flag: '🇳🇬' },
  { code: 'MK', name: 'Macedonian', flag: '🇲🇰' },
  { code: 'NO', name: 'Norwegian', flag: '🇳🇴' },
  { code: 'OM', name: 'Omani', flag: '🇴🇲' },
  { code: 'PK', name: 'Pakistani', flag: '🇵🇰' },
  { code: 'PW', name: 'Palauan', flag: '🇵🇼' },
  { code: 'PA', name: 'Panamanian', flag: '🇵🇦' },
  { code: 'PG', name: 'Papua New Guinean', flag: '🇵🇬' },
  { code: 'PY', name: 'Paraguayan', flag: '🇵🇾' },
  { code: 'PE', name: 'Peruvian', flag: '🇵🇪' },
  { code: 'PH', name: 'Filipino', flag: '🇵🇭' },
  { code: 'PL', name: 'Polish', flag: '🇵🇱' },
  { code: 'PT', name: 'Portuguese', flag: '🇵🇹' },
  { code: 'QA', name: 'Qatari', flag: '🇶🇦' },
  { code: 'RO', name: 'Romanian', flag: '🇷🇴' },
  { code: 'RU', name: 'Russian', flag: '🇷🇺' },
  { code: 'RW', name: 'Rwandan', flag: '🇷🇼' },
  { code: 'KN', name: 'Kittitian and Nevisian', flag: '🇰🇳' },
  { code: 'LC', name: 'Saint Lucian', flag: '🇱🇨' },
  { code: 'VC', name: 'Vincentian', flag: '🇻🇨' },
  { code: 'WS', name: 'Samoan', flag: '🇼🇸' },
  { code: 'SM', name: 'Sammarinese', flag: '🇸🇲' },
  { code: 'ST', name: 'São Toméan', flag: '🇸🇹' },
  { code: 'SA', name: 'Saudi', flag: '🇸🇦' },
  { code: 'SN', name: 'Senegalese', flag: '🇸🇳' },
  { code: 'RS', name: 'Serbian', flag: '🇷🇸' },
  { code: 'SC', name: 'Seychellois', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leonean', flag: '🇸🇱' },
  { code: 'SG', name: 'Singaporean', flag: '🇸🇬' },
  { code: 'SK', name: 'Slovak', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenian', flag: '🇸🇮' },
  { code: 'SB', name: 'Solomon Islander', flag: '🇸🇧' },
  { code: 'SO', name: 'Somali', flag: '🇸🇴' },
  { code: 'ZA', name: 'South African', flag: '🇿🇦' },
  { code: 'SS', name: 'South Sudanese', flag: '🇸🇸' },
  { code: 'ES', name: 'Spanish', flag: '🇪🇸' },
  { code: 'LK', name: 'Sri Lankan', flag: '🇱🇰' },
  { code: 'SD', name: 'Sudanese', flag: '🇸🇩' },
  { code: 'SR', name: 'Surinamese', flag: '🇸🇷' },
  { code: 'SE', name: 'Swedish', flag: '🇸🇪' },
  { code: 'CH', name: 'Swiss', flag: '🇨🇭' },
  { code: 'SY', name: 'Syrian', flag: '🇸🇾' },
  { code: 'TW', name: 'Taiwanese', flag: '🇹🇼' },
  { code: 'TJ', name: 'Tajik', flag: '🇹🇯' },
  { code: 'TZ', name: 'Tanzanian', flag: '🇹🇿' },
  { code: 'TH', name: 'Thai', flag: '🇹🇭' },
  { code: 'TL', name: 'Timorese', flag: '🇹🇱' },
  { code: 'TG', name: 'Togolese', flag: '🇹🇬' },
  { code: 'TO', name: 'Tongan', flag: '🇹🇴' },
  { code: 'TT', name: 'Trinidadian and Tobagonian', flag: '🇹🇹' },
  { code: 'TN', name: 'Tunisian', flag: '🇹🇳' },
  { code: 'TR', name: 'Turkish', flag: '🇹🇷' },
  { code: 'TM', name: 'Turkmen', flag: '🇹🇲' },
  { code: 'TV', name: 'Tuvaluan', flag: '🇹🇻' },
  { code: 'UG', name: 'Ugandan', flag: '🇺🇬' },
  { code: 'UA', name: 'Ukrainian', flag: '🇺🇦' },
  { code: 'AE', name: 'Emirati', flag: '🇦🇪' },
  { code: 'GB', name: 'British', flag: '🇬🇧' },
  { code: 'US', name: 'American', flag: '🇺🇸' },
  { code: 'UY', name: 'Uruguayan', flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbek', flag: '🇺🇿' },
  { code: 'VU', name: 'Ni-Vanuatu', flag: '🇻🇺' },
  { code: 'VE', name: 'Venezuelan', flag: '🇻🇪' },
  { code: 'VN', name: 'Vietnamese', flag: '🇻🇳' },
  { code: 'YE', name: 'Yemeni', flag: '🇾🇪' },
  { code: 'ZM', name: 'Zambian', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwean', flag: '🇿🇼' },
]
